### ISSUE TITLE
Switch from Bun to Node

### ISSUE THREAD

**Issue by mkermani144** [ConnecMent/dydx-bot#30]
## Prerequisites
- [x] https://github.com/ConnecMent/bank/issues/33
- [x] https://github.com/ConnecMent/bank/issues/34

## Description
- [x] Remove all bun-related files and codes (e.g. bun lock file, its `@types` package, etc.)
- [x] Choose a package manager of your choice (`npm` or `pnpm` preferred), install project dependencies and commit its lock file
- [x] Setup `dotenv` for reading env vars

**Comment by Jarred-Sumner** [comment]
Sorry to hear. What made you switch away from Bun?

**Comment by mkermani144** [comment]
@Jarred-Sumner 
It's nice to see your comments here! Really appreciate it.
We had some problems with the `fetch` implementation in Bun, which caused one of the packages not to work as expected. So yeah, unfortunately we had to switch.
